### ISSUE TITLE
Troubles with R# 2019.2

### ISSUE THREAD

**Issue by laurentkempe** [zvirja/ReSharperHelpers#10]
First, thanks for your great extension! One of the first extension I install after an update of R#

Yesterday I updated to R# 2019.2 and to the latest of ReSharperHelpers and had lots of different issues in R# itself, which all go away when I uninstall ReSharperHelpers.

For example when I use search anywhere, I see correct result but when I select one result by clicking on it or pressing enter, then the file is not opened.
When I use, member list (ctrl-F12) and select a result it is ending up the same by not navigating to the member select.
Got to declaration, the same, no navigation.

I hope you will be able to reproduce it and fix it!

**Comment by zvirja** [comment]
Hi,

Thanks for raising the issue. Could you please double check that you installed v5.4.0? It's the only version compatible with R# 2019.2.

It's very strange issue, as this extension doesn't affect those areas. I've just tested it locally and the issue is not reproducible neither 😕 

Which version of VS do you use? Does it happen with all the projects?

Thanks!

**Comment by laurentkempe** [comment]
Hi Alex

I have re-installed the extension and now it works! It super weird thing!
Just after the update of R# to 2019.2, I installed your extension and [TestLinker](https://github.com/matkoch/resharper-testlinker). Then started to have all the crazy issues till a colleague told me that the issue came from your extension, I uninstalled it and it worked again.
I am on Visual Studio 2019 16.1.5. 
I didn't try on different projects.

Welcome
