### ISSUE TITLE
Possible to Assign Namespace?

### ISSUE THREAD

**Issue by Mike-E-angelo** [zvirja/ReSharperHelpers#9]
Consider the following assemblies:

```
Namespace
Namespace.Other
Namespace.Testing
```

I would like to have `Namespace.Testing` handle the tests for both assemblies.  When a test from `Namespace.Other` is generated, ideally it would go into `Namespace.Testing.Other`.  I tried playing around with this and didn't have much luck, so wanted to ping here to see if there's a consideration that I am unaware of.  Thank you for any assistance!

**Comment by Mike-EEE** [comment]
FWIW the tests are generating and everything is working, it's that the tests are placed in the root testing namespace `Namespace.Testing` rather than the ideal `Namespace.Testing.Other`.  If I move the test to that folder, the related files finds it there, too.  So, it's just the location of the created file that is the issue here.

**Comment by Mike-EEE** [comment]
Alright, I got this issue posted in the right place.  _Very_ sorry again for the confusion.  Part of the problem of having so many extensions installed.  Sounds like you might be able to leverage some consideration/cycles towards this still, however, so maybe not all is not lost, if not my pride. 😆 😢

**Comment by zvirja** [comment]
Good day! I've just implemented the feature and new version should be published soon. Read here: https://github.com/zvirja/ReSharperHelpers#test-project-sub-namespace.

Now you can configure sub-namespace via `.editorconfig` file. It works really nice. You can even configure it per folder if there is a need 😊 

Not sure it's still brings value to you and implemented it because I need it in my new project 😅
